# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
eb setenv POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_HOST=$POSTGRES_HOST POSTGRES_DB=$POSTGRES_DB AWS_BUCKET=$AWS_BUCKET AWS_REGION=$AWS_REGION JWT_SECRET=$JWT_SECRET




export AWS_PROFILE=default
export URL=http://localhost:8100